export default {
  DEFAULT_API_FAILURE: "DEFAULT_API_FAILURE",

  NEW_SIGNUP_REQUEST: "NEW_SIGNUP_REQUEST",
  NEW_SIGNUP_SUCCESS: "NEW_SIGNUP_SUCCESS",
  NEW_SIGNUP_FAILURE: "NEW_SIGNUP_FAILURE",

  SIGNIN_REQUEST: "SIGNIN_REQUEST",
  SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
  SIGNIN_FAILURE: "SIGNIN_FAILURE",

  FORGOT_PASSWORD_REQUEST: "FORGOT_PASSWORD_REQUEST",
  FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
  FORGOT_PASSWORD_FAILURE: "FORGOT_PASSWORD_FAILURE",

  GET_PRIVACY_POLICY_REQUEST: "GET_PRIVACY_POLICY_REQUEST",
  GET_PRIVACY_POLICY_SUCCESS: "GET_PRIVACY_POLICY_SUCCESS",
  GET_PRIVACY_POLICY_FAILURE: "GET_PRIVACY_POLICY_FAILURE",
  ADD_PROFILE_REQUEST: "ADD_PROFILE_REQUEST",
  ADD_PROFILE_SUCCESS: "ADD_PROFILE_SUCCESS",
  ADD_PROFILE_FAILURE: "ADD_PROFILE_FAILURE",

  CHANGE_PASSWORD_REQUEST: "CHANGE_PASSWORD_REQUEST",
  CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS",
  CHANGE_PASSWORD_FAILURE: "CHANGE_PASSWORD_FAILURE",

  UPLOAD_PROFILE_REQUEST: "UPLOAD_PROFILE_REQUEST",
  UPLOAD_PROFILE_SUCCESS: "UPLOAD_PROFILE_SUCCESS",
  UPLOAD_PROFILE_FAILURE: "UPLOAD_PROFILE_FAILURE",

  EDIT_PROFILE_REQUEST: "EDIT_PROFILE_REQUEST",
  EDIT_PROFILE_SUCCESS: "EDIT_PROFILE_SUCCESS",
  EDIT_PROFILE_FAILURE: "EDIT_PROFILE_FAILURE",
  UPDATE_COUNT: "UPDATE_COUNT",

  GET_SEEKER_DETAILS_REQUEST: "GET_SEEKER_DETAILS_REQUEST",
  GET_SEEKER_DETAILS_SUCCESS: "GET_SEEKER_DETAILS_SUCCESS",
  GET_SEEKER_DETAILS_FAILURE: "GET_SEEKER_DETAILS_FAILURE",

  GET_PROVIDER_DETAILS_REQUEST: "GET_PROVIDER_DETAILS_REQUEST",
  GET_PROVIDER_DETAILS_SUCCESS: "GET_PROVIDER_DETAILS_SUCCESS",
  GET_PROVIDER_DETAILS_FAILURE: "GET_PROVIDER_DETAILS_FAILURE",

  UPLOAD_LOGO_REQUEST: "UPLOAD_LOGO_REQUEST",
  UPLOAD_LOGO_SUCCESS: "UPLOAD_LOGO_SUCCESS",
  UPLOAD_LOGO_FAILURE: "UPLOAD_LOGO_FAILURE",

  GET_USER_DETAILS_REQUEST: "GET_USER_DETAILS_REQUEST",
  GET_USER_DETAILS_SUCCESS: "GET_USER_DETAILS_SUCCESS",
  GET_USER_DETAILS_FAILURE: "GET_USER_DETAILS_FAILURE",

  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
  ADD_SAVED_JOB_LIST: "ADD_SAVED_JOB_LIST",

  GET_PROVIDER_POST_REQUEST: "GET_PROVIDER_POST_REQUEST",
  GET_PROVIDER_POST_SUCCESS: "GET_PROVIDER_POST_SUCCESS",
  GET_PROVIDER_POST_FAILURE: "GET_PROVIDER_POST_FAILURE",

  GET_SEEKER_POST_REQUEST: "GET_SEEKER_POST_REQUEST",
  GET_SEEKER_POST_SUCCESS: "GET_SEEKER_POST_SUCCESS",
  GET_SEEKER_POST_FAILURE: "GET_SEEKER_POST_FAILURE",

  RESET_SEEKER_POSTS: "RESET_SEEKER_POSTS",

  GET_POST_DETAILS_REQUEST: "GET_POST_DETAILS_REQUEST",
  GET_POST_DETAILS_SUCCESS: "GET_POST_DETAILS_SUCCESS",
  GET_POST_DETAILS_FAILURE: "GET_POST_DETAILS_FAILURE",

  RESET_PROVIDER_POSTS: "RESET_PROVIDER_POSTS",

  GET_JOB_DETAILS_REQUEST: "GET_JOB_DETAILS_REQUEST",
  GET_JOB_DETAILS_SUCCESS: "GET_JOB_DETAILS_SUCCESS",
  GET_JOB_DETAILS_FAILURE: "GET_JOB_DETAILS_FAILURE",

  ADD_HIRING_POST_REQUEST: "ADD_HIRING_POST_REQUEST",
  ADD_HIRING_POST_SUCCESS: "ADD_HIRING_POST_SUCCESS",
  ADD_HIRING_POST_FAILURE: "ADD_HIRING_POST_FAILURE",
  SEARCHED: "SEARCHED",

  ADD_JOB_IMAGE_REQUEST: "ADD_JOB_IMAGE_REQUEST",
  ADD_JOB_IMAGE_SUCCESS: "ADD_JOB_IMAGE_SUCCESS",
  ADD_JOB_IMAGE_FAILURE: "ADD_JOB_IMAGE_FAILURE",

  GET_JOB_APPLICANT_REQUEST: "GET_JOB_APPLICANT_REQUEST",
  GET_JOB_APPLICANT_SUCCESS: "GET_JOB_APPLICANT_SUCCESS",
  GET_JOB_APPLICANT_FAILURE: "GET_JOB_APPLICANT_FAILURE",

  GET_JOB_APPLICANT_LISTING_REQUEST: "GET_JOB_APPLICANT_LISTING_REQUEST",
  GET_JOB_APPLICANT_LISTING_SUCCESS: "GET_JOB_APPLICANT_LISTING_SUCCESS ",
  GET_JOB_APPLICANT_LISTING_FAILURE: "GET_JOB_APPLICANT_LISTING_FAILURE",

  GET_APPLICANT_PROFILE_REQUEST: "GET_APPLICANT_PROFILE_REQUEST",
  GET_APPLICANT_PROFILE_SUCCESS: "GET_APPLICANT_PROFILE_SUCCESS",
  GET_APPLICANT_PROFILE_FAILURE: "GET_APPLICANT_PROFILE_FAILURE",

  UPDATE_JOB_REQUEST: "UPDATE_JOB_REQUEST",
  UPDATE_JOB_SUCCESS: "UPDATE_JOB_SUCCESS",
  UPDATE_JOB_FAILURE: "UPDATE_JOB_FAILURE",
  CLEAR_COMPANY_PROFILE: "CLEAR_COMPANY_PROFILE",
  DELETE_POST_REQUEST: "DELETE_POST_REQUEST",
  DELETE_POST_SUCCESS: "DELETE_POST_SUCCESS",
  DELETE_POST_FAILURE: "DELETE_POST_FAILURE",
  REMOVE_DELETED_POST: "REMOVE_DELETED_POST",
  REMOVE_DELETED_JOB: "REMOVE_DELETED_JOB",
  REMOVE_SAVED_POST: "REMOVE_SAVED_POST",

  CONTACT_US_REQUEST: "CONTACT_US_REQUEST",
  CONTACT_US_SUCCESS: "CONTACT_US_SUCCESS",
  CONTACT_US_FAILURE: "CONTACT_US_FAILURE",

  GET_TERMS_REQUEST: "GET_TERMS_REQUEST",
  GET_TERMS_SUCCESS: "GET_TERMS_SUCCESS",
  GET_TERMS_FAILURE: "GET_TERMS_FAILURE",

  UPLOAD_DOCUMENT_REQUEST: "UPLOAD_DOCUMENT_REQUEST",
  UPLOAD_DOCUMENT_SUCCESS: "UPLOAD_DOCUMENT_SUCCESS",
  UPLOAD_DOCUMENT_FAILURE: "UPLOAD_DOCUMENT_FAILURE",

  GET_PROVIDER_JOB_DETAILS_REQUEST: "GET_PROVIDER_JOB_DETAILS_REQUEST",
  GET_PROVIDER_JOB_DETAILS_SUCCESS: "GET_PROVIDER_JOB_DETAILS_SUCCESS",
  GET_PROVIDER_JOB_DETAILS_FAILURE: "GET_PROVIDER_JOB_DETAILS_FAILURE",

  GET_SEEKER_JOB_DETAILS_REQUEST: "GET_SEEKER_JOB_DETAILS_REQUEST",
  GET_SEEKER_JOB_DETAILS_SUCCESS: "GET_SEEKER_JOB_DETAILS_SUCCESS",
  GET_SEEKER_JOB_DETAILS_FAILURE: "GET_SEEKER_JOB_DETAILS_FAILURE",

  CLEAR_POST_DETAILS: "CLEAR_POST_DETAILS",
  CLEAR_POSTS: "CLEAR_POSTS",
  CLEAR_JOB_DETAILS: "CLEAR_JOB_DETAILS",

  GET_POLICY_REQUEST: "GET_POLICY_REQUEST",
  GET_POLICY_SUCCESS: "GET_POLICY_SUCCESS",
  GET_POLICY_FAILURE: "GET_POLICY_FAILURE",

  SAVE_JOB_REQUEST: "SAVE_JOB_REQUEST",
  SAVE_JOB_SUCCESS: "SAVE_JOB_SUCCESS",
  SAVE_JOB_FAILURE: "SAVE_JOB_FAILURE",

  SHARE_JOB_REQUEST: "SHARE_JOB_REQUEST",
  SHARE_JOB_SUCCESS: "SHARE_JOB_SUCCESS",
  SHARE_JOB_FAILURE: "SHARE_JOB_FAILURE",

  GET_LATEST_JOB_REQUEST: "GET_LATEST_JOB_REQUEST",
  GET_LATEST_JOB_SUCCESS: "GET_LATEST_JOB_SUCCESS",
  GET_LATEST_JOB_FAILURE: "GET_LATEST_JOB_FAILURE",

  GET_SAVED_LISTING_REQUEST: "GET_SAVED_LISTING_REQUEST",
  GET_SAVED_LISTING_SUCCESS: "GET_SAVED_LISTING_SUCCESS",
  GET_SAVED_LISTING_FAILURE: "GET_SAVED_LISTING_FAILURE",

  REJECT_APPLICANT_REQUEST: "REJECT_APPLICANT_REQUEST",
  REJECT_APPLICANT_SUCCESS: "REJECT_APPLICANT_SUCCESS",
  REJECT_APPLICANT_FAILURE: "REJECT_APPLICANT_FAILURE",

  SCHEDULE_INTERVIEW_REQUEST: "SCHEDULE_INTERVIEW_REQUEST",
  SCHEDULE_INTERVIEW_SUCCESS: "SCHEDULE_INTERVIEW_SUCCESS",
  SCHEDULE_INTERVIEW_FAILURE: "SCHEDULE_INTERVIEW_FAILURE",

  SEEKER_SCHEDULE_INTERVIEW_REQUEST: "SEEKER_SCHEDULE_INTERVIEW_REQUEST",
  SEEKER_SCHEDULE_INTERVIEW_SUCCESS: "SEEKER_SCHEDULE_INTERVIEW_SUCCESS",
  SEEKER_SCHEDULE_INTERVIEW_FAILURE: "SEEKER_SCHEDULE_INTERVIEW_FAILURE",

  RESCHEDULE_INTERVIEW_REQUEST: "RESCHEDULE_INTERVIEW_REQUEST",
  RESCHEDULE_INTERVIEW_SUCCESS: "RESCHEDULE_INTERVIEW_SUCCESS",
  RESCHEDULE_INTERVIEW_FAILURE: "RESCHEDULE_INTERVIEW_FAILURE",

  CANCEL_INTERVIEW_REQUEST: "CANCEL_INTERVIEW_REQUEST",
  CANCEL_INTERVIEW_SUCCESS: "CANCEL_INTERVIEW_SUCCESS",
  CANCEL_INTERVIEW_FAILURE: "CANCEL_INTERVIEW_FAILURE",

  DOWNLOAD_RESUME_REQUEST: "DOWNLOAD_RESUME_REQUEST",
  DOWNLOAD_RESUME_SUCCESS: "DOWNLOAD_RESUME_SUCCESS",
  DOWNLOAD_RESUME_FAILURE: "DOWNLOAD_RESUME_FAILURE",

  DOWNLOAD_AUDIO_REQUEST: "DOWNLOAD_AUDIO_REQUEST",
  DOWNLOAD_AUDIO_SUCCESS: "DOWNLOAD_AUDIO_SUCCESS",
  DOWNLOAD_AUDIO_FAILURE: "DOWNLOAD_AUDIO_FAILURE",

  GET_APPLIED_JOBS_REQUEST: "GET_APPLIED_JOBS_REQUEST",
  GET_APPLIED_JOBS_SUCCESS: "GET_APPLIED_JOBS_SUCCESS",
  GET_APPLIED_JOBS_FAILURE: "GET_APPLIED_JOBS_FAILURE",

  APPLY_JOB_REQUEST: "APPLY_JOB_REQUEST",
  APPLY_JOB_SUCCESS: "APPLY_JOB_SUCCESS",
  APPLY_JOB_FAILURE: "APPLY_JOB_FAILURE",

  CLEAR_SCHEDULE_REQUEST: "CLEAR_SCHEDULE_REQUEST",
  CLEAR_SCHEDULE_SUCCESS: "CLEAR_SCHEDULE_SUCCESS",
  CLEAR_SCHEDULE_FAILURE: "CLEAR_SCHEDULE_FAILURE",

  SEARCH_ADDRESS_LISTING_REQUEST: "SEARCH_ADDRESS_LISTING_REQUEST",
  SEARCH_ADDRESS_LISTING_SUCCESS: "SEARCH_ADDRESS_LISTING_SUCCESS",
  SEARCH_ADDRESS_LISTING_FAILURE: "SEARCH_ADDRESS_LISTING_FAILURE",

  GET_ADDRESS_DETAILS_REQUEST: "GET_ADDRESS_DETAILS_REQUEST",
  GET_ADDRESS_DETAILS_SUCCESS: "GET_ADDRESS_DETAILS_SUCCESS",
  GET_ADDRESS_DETAILS_FAILURE: "GET_ADDRESS_DETAILS_FAILURE",

  FETCH_NEARBY_JOBS_REQUEST: "FETCH_NEARBY_JOBS_REQUEST",
  FETCH_NEARBY_JOBS_SUCCESS: "FETCH_NEARBY_JOBS_SUCCESS",
  FETCH_NEARBY_JOBS_FAILURE: "FETCH_NEARBY_JOBS_FAILURE",

  SEARCH_MYJOBS: "SEARCH_MYJOBS",
  SEARCH_SAVED_JOBS: "SEARCH_SAVED_JOBS",

  DELETE_JOB_REQUEST: "DELETE_JOB_REQUEST",
  DELETE_JOB_SUCCESS: "DELETE_JOB_SUCCESS",
  DELETE_JOB_FAILURE: "DELETE_JOB_FAILURE",
  CLEAR_JOB_APPPLICANT_LIST: "CLEAR_JOB_APPPLICANT_LIST",

  REMOVE_REJECTED_APPLICANT: "REMOVE_REJECTED_APPLICANT",
  RESET_MYJOBS: "RESET_MYJOBS",
  UPDATE_APPLY_STATUS: "UPDATE_APPLY_STATUS",
  RESET_MY_JOBS: "RESET_MY_JOBS",
  CLEAR_APPLICANT_PROFILE: "CLEAR_APPLICANT_PROFILE",
  MARK_SEEKER_VIEW: "MARK_SEEKER_VIEW",
};
