export default {
  DEFAULT_API_FAILURE: "DEFAULT_API_FAILURE",

  NEW_SIGNUP_REQUEST: "NEW_SIGNUP_REQUEST",
  NEW_SIGNUP_SUCCESS: "NEW_SIGNUP_SUCCESS",
  NEW_SIGNUP_FAILURE: "NEW_SIGNUP_FAILURE",

  SIGNIN_REQUEST: "SIGNIN_REQUEST",
  SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
  SIGNIN_FAILURE: "SIGNIN_FAILURE",

  FETCH_TEAS_REQUEST: "FETCH_TEAS_REQUEST",
  FETCH_TEAS_SUCCESS: "FETCH_TEAS_SUCCESS",
  FETCH_TEAS_FAILURE: "FETCH_TEAS_FAILURE",

  ADD_TEA_REQUEST: "ADD_TEA_REQUEST",
  ADD_TEA_SUCCESS: "ADD_TEA_SUCCESS",
  ADD_TEA_FAILURE: "ADD_TEA_FAILURE",

  UPDATE_TEA_REQUEST: "UPDATE_TEA_REQUEST",
  UPDATE_TEA_SUCCESS: "UPDATE_TEA_SUCCESS",
  UPDATE_TEA_FAILURE: "UPDATE_TEA_FAILURE",

};
